@register_info_admin = {"email": "admin@example.com","user_id": "admin","username": "アドミン","password": "password"}
@register_info_01 = {"email": "user01@example.com","user_id": "user01","username": "ユーザー01","password": "passw0rd01"}
@register_info_02 = {"email": "user02@example.com","user_id": "user02","username": "ユーザー02","password": "passw0rd02"}
@user_info_admin = {"user_id": "admin","password": "password"}
@user_info_01 = {"user_id": "user01","password": "passw0rd01"}
@user_info_02 = {"user_id": "user02","password": "passw0rd02"}
@token = {{login.response.body.$.auth_token}}
@user_id = {{me.response.body.$.user_id}}
@username = {{me.response.body.$.username}}

# @name login
POST http://127.0.0.1:8000/api/v1/auth/token/login/
content-type: application/json

{{register_info_01}}
###

# @name logout
POST http://127.0.0.1:8000/api/v1/auth/token/logout/
Authorization: token {{token}}


###

# @name all_profile
GET http://127.0.0.1:8000/api/v1/profiles/
Authorization: token {{token}}


###

# @name profile
GET http://127.0.0.1:8000/api/v1/profiles/{{user_id}}/
Authorization: token {{token}}


###
PUT http://127.0.0.1:8000/api/v1/profiles/{{user_id}}/
Authorization: token {{token}}
content-type: application/json

{
  "user": {
    "user_id": "user02",
    "username": "ユーザー02_権限テスト"
  },
  "description": null,
  "location": "",
  "date_joined": "2021-07-10T21:42:10.767778+09:00",
  "updated_on": "2021-07-10T21:42:10.767778+09:00",
  "is_organizer": false
}

###
PATCH http://127.0.0.1:8000/api/v1/profiles/{{user_id}}/
Authorization: token {{token}}
content-type: application/json



###

# @name user
GET http://127.0.0.1:8000/api/v1/users/
Authorization: token {{token}}


###

# @name register
POST http://127.0.0.1:8000/api/v1/users/
content-type: application/json

{{register_info_01}}

###

# @name me
GET http://127.0.0.1:8000/api/v1/users/me/
Authorization: token {{token}}


###
PUT http://127.0.0.1:8000/api/v1/users/me/
Authorization: token {{token}}
content-type: application/json



###
PATCH http://127.0.0.1:8000/api/v1/users/me/
Authorization: token {{token}}
content-type: application/json



###
DELETE http://127.0.0.1:8000/api/v1/users/me/
Authorization: token {{token}}
content-type: application/json



###

# @name users
GET http://127.0.0.1:8000/api/v1/users/{{user_id}}/
Authorization: token {{token}}


###
PUT http://127.0.0.1:8000/api/v1/users/{{user_id}}/
Authorization: token {{token}}
content-type: application/json



###
PATCH http://127.0.0.1:8000/api/v1/users/{{user_id}}/
Authorization: token {{token}}
content-type: application/json


###
DELETE http://127.0.0.1:8000/api/v1/users/{{user_id}}/
Authorization: token {{token}}


###

# @name set_password
POST http://127.0.0.1:8000/api/v1/users/set_password/
Authorization: token {{token}}
content-type: application/json

{"current_password":"passw0rd011", "new_password": "passw0rd01"}

###

# @name set_user_id
POST http://127.0.0.1:8000/api/v1/users/set_user_id/
Authorization: token {{token}}
content-type: application/json

{"current_password": "passw0rd01", "new_user_id": "user01"}

###